### PR TITLE
ENH: improvements and additions from XCS testing

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Add generic QMini and EpicsMotor loader (environment variable-configured PV prefixes)
* Remove status object prefix from window title if unspecified (as we are not propagating scan settings to EPICS just yet)

## Motivation and Context
Testing at XCS with class 4 laser

## How Has This Been Tested?
Interactive testing

## Where Has This Been Documented?
This PR text

### CODE REVIEW

**Comment by slactjohnson** [comment]
Let me know when this is ready (I think you said you wanted to add some things) and then I'll take a closer look. 
Thanks again for all your hard work!

**Comment by klauer** [comment]
[30b1fb6](https://github.com/pcdshub/las-dispersion-scan/pull/5/commits/30b1fb65c3f46de0d7307ffcba40f7e58a79c402) added per-position scan data plots but not reconstructed pulse plots (TODO)

**Comment by klauer** [comment]
Most of the requests are in. I updated the checklist from #6 as I addressed them.

**Comment by klauer** [comment]
Fixed up a few more things. Hopefully this implements all that was requested for this run.
Also added user-specific saving/reloading of all parameters because it was bugging me.

I've only tested it with the simulation IOC. If anything doesn't work, try to patch it if possible or roll back prior to the issue.

**Comment by slactjohnson** [comment]
Got some feedback from the laser group. They said all new features seemed to work well. They have a few minor tweaks they want to make, but I will discuss with them more later this week. We'll be setting up for another test in the laser lab with a different motor.

**Review by slactjohnson — APPROVED** [review]
LGTM!

**Pull request merged**
